# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    ## H2
    #url: jdbc:h2:mem:mydb
    
    url: jdbc:postgresql://localhost:5432/testjava
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
  h2:
    console:
      enabled: true



  jpa:
    hibernate:
      ddl-auto: update
     


jwt:
  header: Authorization
  secret: tasksSecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
      

#logging:
#  level:
#    org.springframework:
#      security: DEBUG
